<?php

/**
 * Plugin Name:     Disable WebP
 * Version:         1.0.0
 * Description:     A small plugin to disable the new WebP standard in the settings.
 * Author:          URBAN BASE
 * Author URI:      https://urban-base.net/?utm_source=ubdw_author_uri
 * Copyright:       Mario Maier
 * Text Domain:     ubdw
 * Domain Path:     /languages
 * License:         GPLv3
 * License URI:     https://www.gnu.org/licenses/quick-guide-gplv3
 */

if (!defined('ABSPATH'))
    die;

define('UBDW__TITLE', 'Disable WebP');
define('UBDW__SLUG', 'disable-webp');
define('UBDW__VERSION', '1.0.0');

load_plugin_textdomain('ubdw', false, dirname(plugin_basename(__FILE__)) . '/languages');

if (empty(get_option('ubdw_disable_webp')))
    add_option('ubdw_disable_webp', 'on');

if (get_option('ubdw_disable_webp') == 'on')
    add_filter('wp_upload_image_mime_transforms', '__return_empty_array');

function ubdw_register_options_page()
{
    add_options_page(UBDW__TITLE, esc_html__('Disable WebP', 'ubdw'), 'manage_options', UBDW__SLUG, 'ubdw_options_page');
}
add_action('admin_menu', 'ubdw_register_options_page');

function ubdw_options_page()
{
    if (isset($_POST['submit']) && wp_verify_nonce($_POST['nonce'], 'save-ubdw-settings')) {
        if ($_POST['disable-webp'] == 'on')
            update_option('ubdw_disable_webp', 'on');
        else
            update_option('ubdw_disable_webp', '');
    }
?>
    <div class="wrap">
        <h1 class="wp-heading-inline"><?= UBDW__TITLE ?></h1>
        <hr class="wp-header-end">
        <br>
        <div class="postbox">
            <div class="inside">
                <p><?= esc_html__('In WordPress 6.1, a WebP version is generated by default when an image is uploaded and displayed in the frontend.', 'ubdw') ?></p>
                <p><?= esc_html__('The WebP format generally compresses the images well.', 'ubdw') ?></p>
                <p><?= esc_html__('But in certain cases the WebP version can be larger than the original image.', 'ubdw') ?></p>
                <p><?= esc_html__('If WebP causes problems on your website, you can disable this function here.', 'ubdw') ?></p>
                <form action="" method="post">
                    <input type="checkbox" name="disable-webp" <?php if (get_option('ubdw_disable_webp') == 'on') {
                                                                    echo 'checked="checked"';
                                                                } ?>>
                    <b><?= esc_html__('Disable WebP', 'ubdw') ?></b>
                    <br><br>
                    <input type="hidden" name="nonce" value="<?= wp_create_nonce('save-ubdw-settings') ?>">
                    <input class="button-primary" type="submit" name="submit" value="<?= esc_html__('Save changes', 'ubdw') ?>">
                </form>
            </div>
        </div>
        <div class="postbox">
            <div class="inside">
                <p><b><?= UBDW__TITLE ?> v<?= UBDW__VERSION ?></b></p>
                <p><?= esc_html__('If you like', 'ubdw') ?> <?= UBDW__TITLE ?>, <?= esc_html__('then write a', 'ubdw') ?> <a href="https://wordpress.org/support/plugin/disable-webp/reviews/?filter=5#postform" target="_blank" title="<?= UBDW__TITLE ?> rating">★★★★★ <?= esc_html__('rating', 'ubdw') ?></a>. <?= esc_html__('You would help me a lot to make the plugin known.', 'ubdw') ?></p>
            </div>
        </div>
    </div>
<?php
}
